name: 'Build and Deploy to Cloud Run'

on:
  push:
    branches:
      - 'main'

env:
  PROJECT_ID: 'action-450507'
  REGION: 'us-central1'
  SERVICE: 'github-auto'
  WORKLOAD_IDENTITY_PROVIDER: 'projects/733182017872/locations/global/workloadIdentityPools/auto-build/providers/ponpon'

jobs:
  deploy:
    runs-on: 'ubuntu-latest'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4'

      - name: 'Debug - Show Environment'
        run: |
          echo "Project ID: ${{ env.PROJECT_ID }}"
          echo "Region: ${{ env.REGION }}"
          echo "Service: ${{ env.SERVICE }}"
          echo "Workload Identity Provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}"

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: '${{ env.WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: 'github-action@action-450507.iam.gserviceaccount.com'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Debug - Check Authentication'
        run: |
          echo "Checking gcloud auth..."
          gcloud auth list
          echo "Checking project configuration..."
          gcloud config list
          echo "Checking Artifact Registry access..."
          gcloud artifacts repositories list --location=${{ env.REGION }}

      - name: 'Docker Auth'
        id: docker-auth
        uses: 'docker/login-action@v3'
        with:
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'
          registry: '${{ env.REGION }}-docker.pkg.dev'

      - name: 'Debug - Check Docker'
        run: |
          echo "Checking Docker configuration..."
          docker info
          echo "Listing Docker images..."
          docker images

      - name: 'Build and Push Container'
        run: |-
          set -x
          DOCKER_TAG="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{ github.sha }}"
          echo "Building image: ${DOCKER_TAG}"
          docker build --tag "${DOCKER_TAG}" .
          echo "Pushing image: ${DOCKER_TAG}"
          docker push "${DOCKER_TAG}"

      - name: 'Deploy to Cloud Run'
        id: deploy
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: '${{ env.SERVICE }}'
          region: '${{ env.REGION }}'
          image: '${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{ github.sha }}'

      - name: 'Show Output'
        run: 'echo ${{ steps.deploy.outputs.url }}'