name: 'Build and Deploy to Cloud Run'

on:
  push:
    branches:
      - 'main'

env:
  PROJECT_ID: 'action-450507'
  REGION: 'us-central1'
  SERVICE: 'github-auto'
  WORKLOAD_IDENTITY_PROVIDER: 'projects/733182017872/locations/global/workloadIdentityPools/auto-build/providers/ponpon'

jobs:
  deploy:
    runs-on: 'ubuntu-latest'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4'

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: '${{ env.WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: 'github-action@action-450507.iam.gserviceaccount.com'
          token_format: 'access_token'
          create_credentials_file: true
          
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          project_id: '${{ env.PROJECT_ID }}'
          install_components: 'gke-gcloud-auth-plugin'
          
      - name: 'Configure Docker'
        run: |-
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet
          
      - name: 'Build and Push Container'
        run: |-
          IMAGE_NAME="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}/app:${{ github.sha }}"
          echo "Building image: ${IMAGE_NAME}"
          docker build -t "${IMAGE_NAME}" .
          echo "Pushing image: ${IMAGE_NAME}"
          docker push "${IMAGE_NAME}"

      - name: 'Deploy to Cloud Run'
        id: deploy
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: '${{ env.SERVICE }}'
          region: '${{ env.REGION }}'
          image: '${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}/app:${{ github.sha }}'

      - name: 'Show Output'
        run: 'echo ${{ steps.deploy.outputs.url }}'